name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build code
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          cd ..

      - name: Test code
        run: |
          chmod +x ./build/test_run
          ./build/test_run
          
  deploy-package:
    runs-on: ubuntu-latest
    needs: test-package
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build code
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          cd ..

      - name: Prepare release
        run: |
          mkdir -p publish/lib
          cp ./build/libktnlibc.a ./publish/lib/ktnlibc.a
          cp -r ./include ./publish/
          cp -r ./src ./publish/
          cp ./LICENSE ./publish/
          cp ./README.md ./publish/

      - name: Create lib archive
        run: |
          cd ./publish
          zip -rv9 ../linux-release.zip lib include src LICENSE README.md
          cd ..

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ktnlibc ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload release archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux-release.zip
          asset_name: ktnlibc-${{ github.ref_name }}-linux.zip
          asset_content_type: application/zip
